SELECT P.PRODUCT_ID, P.PRODUCT_NAME, (P.PRICE * O.SUM) AS TOTAL_SALES
FROM FOOD_PRODUCT P
JOIN (
        SELECT PRODUCT_ID, PRODUCE_DATE, SUM(AMOUNT) AS SUM 
        FROM FOOD_ORDER 
        WHERE MONTH(PRODUCE_DATE)='05'
        GROUP BY PRODUCT_ID
) O
ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID;
