-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM APPOINTMENT A
JOIN DOCTOR D ON A.MDDR_ID=D.DR_ID 
JOIN PATIENT P ON P.PT_NO=A.PT_NO
WHERE D.MCDP_CD='CS' AND DATE_FORMAT(A.APNT_YMD,'%Y-%m-%d')='2022-04-13' AND A.APNT_CNCL_YMD IS NULL
ORDER BY A.APNT_YMD;